import { type NextPage } from "next";
import Head from "next/head";
import Footer from "../components/footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <main className="mt-10 flex w-full flex-col items-center justify-center">
          <h1 className="text-4xl font-bold text-white">Todo App</h1>
          <form className="m-5 flex w-full items-center justify-center">
            <input
              type="text"
              placeholder="Type here"
              className="input-bordered input w-full max-w-xs"
            />
            <button className="btn">Add</button>
          </form>
          <div></div>
        </main>
        <Footer />
      </div>
    </>
  );
};

export default Home;
